import { Header } from '@/components/header';
import { AppProviders } from '@/contexts/providers';
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import '../styles/globals.css';

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${openSans.variable} antialiased`}
      >
        <AppProviders>
          <Header />
          <main className="">
            {children}
          </main>
        </AppProviders>
      </body>
    </html>
  );
}
