import { AIModel } from '@/config/AI/config';

export const ENV = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID as string,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET as string,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET as string,
  GOOGLE_GEMINI_API_KEY: process.env.GOOGLE_GEMINI_API_KEY as string,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY as string,
  AI_MODEL: {
    GOOGLE_GEMINI_MODEL: process.env.GOOGLE_GEMINI_MODEL as AIModel,
    OPENAI_MODEL: process.env.OPENAI_MODEL as AIModel,
  },
  REDIS_DATABASE_URL: process.env.REDIS_DATABASE_URL as string,
  GOOGLE_FIREBASE: {
    GOOGLE_FIREBASE_TYPE: process.env.GOOGLE_FIREBASE_TYPE as string,
    GOOGLE_FIREBASE_PROJECT_ID: process.env.GOOGLE_FIREBASE_PROJECT_ID as string,
    GOOGLE_FIREBASE_PRIVATE_KEY_ID: process.env.GOOGLE_FIREBASE_PRIVATE_KEY_ID as string,
    GOOGLE_FIREBASE_PRIVATE_KEY: process.env.GOOGLE_FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n') as string,
    GOOGLE_FIREBASE_CLIENT_EMAIL: process.env.GOOGLE_FIREBASE_CLIENT_EMAIL as string,
    GOOGLE_FIREBASE_CLIENT_ID: process.env.GOOGLE_FIREBASE_CLIENT_ID as string,
    GOOGLE_FIREBASE_AUTH_URI: process.env.GOOGLE_FIREBASE_AUTH_URI as string,
    GOOGLE_FIREBASE_TOKEN_URI: process.env.GOOGLE_FIREBASE_TOKEN_URI as string,
    GOOGLE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL: process.env.GOOGLE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL as string,
    GOOGLE_FIREBASE_CLIENT_X509_CERT_URL: process.env.GOOGLE_FIREBASE_CLIENT_X509_CERT_URL as string,
    GOOGLE_FIREBASE_UNIVERSE_DOMAIN: process.env.GOOGLE_FIREBASE_UNIVERSE_DOMAIN as string,
  },
}